### ISSUE TITLE
How to connect to walkingpad

### ISSUE THREAD

**Issue by WladyX** [klassm/walkingpad_macos_client#2]
I cannot see the walkingpand in the client or in the bluetooth section.
With ph4-walkingpad-ctl i can connect to the walkingpad.
How can i connect with your app?
Thank you for sharing this!
<img width="700" alt="CleanShot 2022-05-21 at 18 56 55@2x" src="https://user-images.githubusercontent.com/1106868/169659782-cdadf89d-483b-4f25-995a-c172beef0ebb.png">

**Comment by klassm** [comment]
Can you try granting the App bluetooth permissions? In the end the app only discovers Bluetooth devices and connects - just the same way as ph4-walkingpad-ctl does.

**Comment by WladyX** [comment]
I've granted the permissions, but nothing changed, same situation as above, for ph4-walkingpad i connect using the mac addr, i am on monterey, `ph4-walkingpad-ctl -a FF0AD562-bla-bla`
<img width="680" alt="image" src="https://user-images.githubusercontent.com/1106868/170942233-37c2c305-123f-4062-bfe9-75839296e5be.png">

Thank you very much for your support.

**Comment by klassm** [comment]
Hm interesting - I have a suspicion. Does the device name by accident not begin with KS-? That is a shortcut I added to not poll all the devices to find the matching one .
Maybe you can try the following build (which has the check removed). I have no clue whether this has any side effects, but maybe it's worth a try.
[Walkingpad Client.zip](https://github.com/klassm/walkingpad_macos_client/files/8816202/Walkingpad.Client.zip)

**Comment by WladyX** [comment]
You nailed it, I have a KingSmith WalkingPad R1 Pro, and with the attached zip app it works!!
Thank you!

**Comment by klassm** [comment]
Cool! Then let's see what breaks ;-)

**Comment by klassm** [comment]
I've released a new version, so will close this now.
